version: "3.6"

networks:
  inside:
    external: false

services:
  db:
    build:
      context: ./services/${DATABASE}
    container_name: "db_${COMPOSE_PROJECT_NAME:-ojs-dev}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-ojs}"
      MYSQL_USER: "${MYSQL_USER:-ojs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-ojs}"
    ports:
      - "${MYSQL_PORT:-3306}:3306"      
    volumes:
      - ./volumes/database:/var/lib/mysql
      - ./volumes/logs/mysql:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
#      - ./volumes/migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  ojs:
    build:
      context: ./services/${PHPVERSION}
    container_name: "app_${COMPOSE_PROJECT_NAME:-ojs-dev}"
    hostname: "${COMPOSE_PROJECT_NAME:-ojs-dev}"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      - ./volumes/plugins:/var/www/html/plugins
      - ./volumes/logs/apache:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
      - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/etc/php7/php.custom.ini
    networks:
      - inside
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: "PHPMyAdmin-${COMPOSE_PROJECT_NAME:-bareDAMP}"
    networks:
      - inside
    depends_on:
      - db
    restart: "no"
    environment:
      PMA_HOST: db
      PMA_PORT: "${MYSQL_PORT:-3306}:3306"
      PMA_USER: root
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_USER: "${MYSQL_USER:-ojs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-ojsPwd}"
      UPLOAD_LIMIT: "${UPLOAD_LIMIT:-512M}"
      MEMORY_LIMIT: "${MEMORY_LIMIT:-512M}"
    ports:
      - "${PHPHMYADMIN_HTTP_PORT:-8082}:80"
      - "${PHPMYADMIN_HTTPS_PORT:-8443}:443"

